language: minimal
services:
  - docker
script:
  - docker build -t awscli .
  - docker run --rm -i -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e ASSUME_ROLE_ARN awscli aws --version
after_success:
  - git config --global user.email "build@travis-ci.com"
  - git config --global user.name "Travis CI"
  - GIT_TAG=$(cat requirements.txt)
  - GIT_TAG=${GIT_TAG#awscli==}
  - git tag -f "$GIT_TAG" -a -m "AWS CLI v$GIT_TAG"
  - <<<$SSH_KEY_PEM_BASE64 base64 -d > ~/.ssh/id_rsa
  - chmod 400  ~/.ssh/id_rsa
  - SSH_REMOTE=ssh://git@github.com/sgreben/docker-awscli.git
  - git push "$SSH_REMOTE" :"$GIT_TAG" || true
  - git push "$SSH_REMOTE" "$GIT_TAG"
branches:
  only:
  - master
